### ISSUE TITLE
реализовать создание команды

### ISSUE THREAD

**Issue by Sterals** [Falconwatch/BankingBattle#17]
Юзер для каждой игры должен иметь право создать команду и добавить в нее других юзеров

**Comment by Falconwatch** [comment]
Не забыть про проверку, что пользователь уже в команде, чтобы не создавалась вторая

**Comment by Sterals** [comment]
Тут еще надо подумать как команды менеджить. Если может быть несколько одновременных игр и юзер может быть в нескольких играх в нескольких командах - что ему показывать

**Comment by Falconwatch** [comment]
> 

Думаю, как есть - пользователь на главной видит список игр, в которых участвует. Надо только контролировать, чтобы пользователь не вписался в одной игре во множество команд

Вообще попахивает новым milestone - управление командой - создам-ка
